### ISSUE TITLE
Wanna say, thank you

### ISSUE THREAD

**Issue by christianTF** [kettenbach-it/FHEM-TPLink-HS110#2]
Hi,

this is not an issue 👍 

Thanks for your program!
I've modified it to use it as a REST webservice: http://www.loxwiki.eu/pages/viewpage.action?pageId=24838213

Feel free if you want to include it to your repo.

[control.zip](https://github.com/kettenbach-it/FHEM-TPLink-HS110/files/1507274/control.zip)

Cheers,
Christian

**Comment by kettenbach-it** [comment]
Thx! Great work!

I added your code to this repository!
