### ISSUE TITLE
Energy reading doesn't work for UK version of the socket HS110(UK)

### ISSUE THREAD

**Issue by LawrenceBeran** [kettenbach-it/FHEM-TPLink-HS110#3]
The HS110(UK) version of the socket works as a HS100 without meter reading.

I fixed my version locally by modifying line 128 of 24_TPLinkHS110.pm from
    if ($json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(EU)") {
to 
    if ($json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(EU)" or $json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(UK)") {

This may not be the best solution as it will not work for other versions of the HS110(??) socket.

**Comment by kettenbach-it** [comment]
Thanks for submitting this code!
I added it to the repository!
