### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by holgerschochwitz** [kettenbach-it/FHEM-TPLink-HS110#4]
Line 128

if ($json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(EU)" or $json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(UK)")) {

correction

if ($json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(EU)" or $json->{'system'}->{'get_sysinfo'}->{'model'} eq "HS110(UK)") {

**Comment by kettenbach-it** [comment]
Fixed in latest commit!
