### ISSUE TITLE
HW Version 2.0

### ISSUE THREAD

**Issue by christianTF** [kettenbach-it/FHEM-TPLink-HS110#9]
Hello Volker,

referring to the Loxone/LoxBerry-Web-Implementation from #2 a user pointed out that his HS110 HW 2.0 version does not work with the (old) control.cgi (https://www.loxforum.com/forum/projektforen/loxberry/plugins/129261-tp-link-hs100-intern-steuern?p=161161#post161161).

You mention the Release 2018-05-17 HW Version 2.0.
- Is this meant to be compatible with HW 2.0 of HS100/HS110 (I think so), and
- is the script with HW 2.0 downwards compatible to sockets with HW 1 firmware?

I then will quickly update your new version to a new control.cgi to also support HW 2.0.

Thanks,
Christian

**Comment by kettenbach-it** [comment]
Hi Christian,

the answers are: yes and yes!

**Comment by christianTF** [comment]
Hi Volker,

it emerges that my updated tplink_hs110_cmd.pl (https://github.com/christianTF/FHEM-TPLink-HS110/blob/master/Loxone/control.cgi) seems not to work with a V2 HS110, but as myself I have no V2 it is difficult to debug.

Is only the 24_TPLinkHS110.pm module compatible with HW2 or should also the tplink_hs110_cmd.pl program should be? 
From the commit perspective, the .pl has not changed for a longer period.

Thanks,
Christian

**Comment by kettenbach-it** [comment]
Hi Christian,

the tplink_hs110_cmd.pl has no support for HW V2, since I don't own a V2 either.
The updates for 24_TPLinkHS110.pm are in a single pull request: 
https://github.com/kettenbach-it/FHEM-TPLink-HS110/pull/6

Porting those to tplink_hs110_cmd.pl should not be hard.

Volker
